sudo: false

dist: xenial

language: java

jdk:
  - openjdk8

script: "mvn -Dorg.slf4j.simpleLogger.showDateTime=true -Dorg.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss test -B"

notifications:
  slack:
    if: branch = master
    on_success: change
    on_failure: always
